### ISSUE TITLE
[bug] Server selects wrong IP on Lan.

### ISSUE THREAD

**Issue by Jeyyu** [TLeonardUK/ds3os#10]
Since the option "ServerIP" is not in the config anymore the server tries to connect to one of my VPN service first instead of Ethernet. I first need to disable all other services before i can connect to the server.

I guess we can just change Network Priority, but is this wanted behavior?

### Screenshot below:

**Green Ethernet IP
Red VPN IP**

![Untitled](https://user-images.githubusercontent.com/60408111/133590774-cf00d410-d89b-42d9-b7ff-f078a1216cae.png)

**Comment by TLeonardUK** [comment]
Yeh the private-ip redirection stuff is fairly recent, so there are some issues there.

I think using the VPN ip is correct behaviour if that has a higher interface priority than the ethernet.

What I think probably needs to happen is if a hostname/ip is defined in these config values:

ServerHostname 
PrivateServerHostname 

Then we should derive the public/private ip from their values,, rather than seperately derived as it currently is.

**Comment by Jeyyu** [comment]
> Then we should derive the public/private ip from their values,, rather than seperately derived as it currently is.

Yeah I think this would be better for overall clearity. 👍

**Comment by Grabisoft** [comment]
> Since the option "ServerIP" is not in the config anymore the server tries to connect to one of my VPN service first instead of Ethernet. I first need to disable all other services before i can connect to the server.
> 
> I guess we can just change Network Priority, but is this wanted behavior?
> 
> ### Screenshot below:
> **Green Ethernet IP Red VPN IP**
> 
> ![Untitled](https://user-images.githubusercontent.com/60408111/133590774-cf00d410-d89b-42d9-b7ff-f078a1216cae.png)

jeyyu can   you give me your email ? i need help in configuring some things, thank you, i cant find your email in your profile

**Comment by Jeyyu** [comment]
email is now visible

**Comment by TLeonardUK** [comment]
Should now behave as I said above. ServerPrivateHostname / ServerHostname are the config values (I changed one of the names slightly).
