### ISSUE TITLE
Able to join server but unable to join session

### ISSUE THREAD

**Issue by Obama1234567** [TLeonardUK/ds3os#121]
So we did port forwarding for my own server and both me and my friend were able to connect to the server and join the game however when we put down the White Sign soapstone it wont appear. However we discovered that if the one of us puts down our White Sign soapstone in the exact spot that the other put their stone down and then get rid of it the others stone will finally appear but when we try to summon each other it will pretend its joining session, itll say being summoned or something like that but 5 seconds later it says unable to join session i cant tell whats causing this. We put passwords, we both used embers at the same time it doesn't seem to be an issue in game as we our also doing it in an area where there is still the main alive. The weird thing is is that summoning each other worked for a at first and for a good while, we were able to summon each other for the first 2 or 3 areas at first but when we reached the crucifix woods we were no longer able to summon each other. Do you know what is going on.

**Comment by SirGouki** [comment]
Are you both similar SL and Weapon upgrades?  DS3 limits co-op and invasions based on BOTH the Soul Level and the Weapon upgrade Level.  You can check if this is impacting you by turning off the coop soul level and weapon level checks in the config file (NOT the ds3osconfig file, the config.json)   The options you're looking for are "DisableLevelMatching" and "DisableWeaponLevelMatching" near line 117 ("SummonSignMatchingParameters"), and restarting the server.  Change them from false to true.  Also, check the server window for any errors.

**Comment by Obama1234567** [comment]
I changed those parameters in the config file and it still did the same thing however the server actually told me something for once before i didnt but now it said "Client attempted to use invalid summon sign, sending back rejection, 1010."

**Comment by SirGouki** [comment]
The only thing I could think of is that somehow the packet is losing data. Without seeing the output of something like Wireshark monitoring the packets (and since I haven't done that through the official servers or seen documentation yet of what they are supposed to look like, that info wouldn't help *me* that much to help you, but it might help the dev of ds3os), I can't confirm that's what's happening for sure, but that's what it seems like is happening.

**Comment by SirGouki** [comment]
Losing packets, and receiving malformed packets are different situations.  The only way to tell if that's the problem is to have a good packet and a bad one next to each other and compare them.  A malformed packet could be a different size, corrupted data, etc.  Also, most "natural" causes of packet loss are preempted by packet corruption usually (at least in my experience in the military when I was in, and at home trouble shooting my own stuff), and it could be going on for a while and no one notice due to most things either dropping the data and re-requesting that information, having some sort of code to preempt what should be there (which shouldn't be relied on because that is a major security flaw), or some other way of preventing it from affecting the user unless its a major case.  It could even be something like the ISP trying to block the traffic on their end for one reason or another.  It's extremely hard to tell without seeing everything involved.

**Comment by Obama1234567** [comment]
Yeah i dont know much about that but do you know how to use hamachi with this i think that might fix the issue but since hamachi doesnt use an external ip i dont know how to implement it

**Comment by Obama1234567** [comment]
Its not working, it doesn't even let me(the host) connect to my own server when i put hamachis ip into both public and private addresses. Finally what do you mean by your last statement my friend is in my network on hamachi and when he tries to connect to my server we do it through the loader that instantly advertises my server.

**Comment by SirGouki** [comment]
what I mean is his config also needs to have your hamachi ip address in it, not his own.  If you're using the server advertising functionality, it *should* still work as long as your config is correct.

As for why you can't connect when you put in your hamachi address, I can't say without seeing your config (don't post it here, security issues).  You should be able to put in **any** valid ip address into that config that is currently in use by your computer and be able to connect to with Dark Souls 3.

**Comment by Obama1234567** [comment]
I decided to try zerotier out and using that we got it to work thanks, the only problem now is that the server will just close every once in a while idk why but its not that big of a deal.

**Comment by Terahertz0** [comment]
I tried using zerotier and hamachi both of them crashed the game, I am using v1.15, regulation version 1.35 with enhanced coop mod
