### ISSUE TITLE
Receiving errors while building

### ISSUE THREAD

**Issue by XilonYakumo** [TLeonardUK/ds3os#122]
I'm receiving errors the following errors while building
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8020	The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	civetweb	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	439	
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3821	Couldn't process file Forms\MainForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	Loader	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3162	
Is there something I am missing or don't understand?

**Comment by SirGouki** [comment]
The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

This is literally telling you what the problem is: the original project is setup to target the build tools for v143 but you're Visual Studio installation is defaulting to a different version.  Do exactly what it says to do (one or the other, NOT ALL!) and it should solve the problem.  

A final note: compiling is for people familiar with programming - if you just want to use the newest release then you should go to the releases page, which has precompiled executables provided.
