### ISSUE TITLE
Win32/Contebrew.A!ml found in Loader.exe

### ISSUE THREAD

**Issue by layzek** [TLeonardUK/ds3os#148]
Trojan found one day after playing on server ServerName by Windows Defender

(Screencap translated with Yandex Translate)
![defender_report](https://user-images.githubusercontent.com/98445947/164929821-cd4cf0cc-3dfb-4001-a838-7f143b7d7f26.jpg)

**Comment by TLeonardUK** [comment]
Known issue. Its a false positive, and there isn't a whole lot I can do about it really.

For reference any detections that end in !ml are machine learning based heuristics rather than actual signature-matches for malware.

Feel free to pass the exe through virus total if you want, you'll see that nothing else flags it. The code is also publically available for you to read/build yourself if you wish. The loader code is tiny.
