### ISSUE TITLE
[BUG] Misjudgement in IsPrivateNetwork() causes trouble using reverse proxies

### ISSUE THREAD

**Issue by KeithCoreDumped** [TLeonardUK/ds3os#172]
## summary

- call to `bool NetIPAddress::IsPrivateNetwork()` from a `NetIPAddress` whose address is `127.0.0.1` should get false instead of true

## details

I have a server at home which has no public IP and a VPS(both running Ubuntu). A reverse proxy(from [fatedier/frp](https://github.com/fatedier/frp)) is set up for port forwarding(TCP 50050, TCP 50000, UDP 50010 will work) so that server can be accessed globally. However, IP addresses of connections through the reverse proxy are always `127.0.0.1`, which are classified as "appears to be on private subnet" by function `bool NetIPAddress::IsPrivateNetwork()` and the connections are redirected to the private IP of the server, which is inaccessible from other subnets. Thus, connections between the game client from other subnets and the server cannot be established.

## fix

- Simply make 127.0.0.1 an exception in `IsPrivateNetwork()` to prevent redirections, as the function is only called to judge whether redirections should take place.

- modification  

https://github.com/TLeonardUK/ds3os/blob/4f3c12e7dc21faebcaaebe680b3b48b2247943ea/Source/Server/Core/Network/NetIPAddress.h#L36

```c++
bool IsPrivateNetwork()
{
    if (Bytes[0] == 127 && Bytes[1] == 0 && Bytes[2] == 0 && Bytes[3] == 1)     // ! 127.0.0.1
        return false;
    return
        Bytes[0] == 127 ||                                                      // 127.*.*.*
        Bytes[0] == 10 ||                                                       // 10.*.*.*
        (Bytes[0] == 172 && Bytes[1] >= 16 && Bytes[1] <= 31) ||                // 172.16.*.* -> 172.31.*.*
        (Bytes[0] == 192 && Bytes[1] == 168);                                   // 192.168.*.*
}
```

**Comment by TLeonardUK** [comment]
This will break people trying to connect from the local machine as it will redirect them to external IP rather than the internal IP that would be expected.

I would suggest if this causes an issue for your setup, that a flag to opt-in to this behaviour in the config file is a better solution.

**Comment by KeithCoreDumped** [comment]
Yes, indeed.

After the modification, connections from the local machine won't be directed to the internal IP, which increases the latency.

However, I noted that others who also use port forwarding seem not to have this problem. Is it because their port forwarding was through the router instead of a reverse proxy running on the local machine? I thought either way would have caused external connections to be redirected to internal IP and lose connection.

Will it work if the client loses connection after redirecting and undoes the redirection?

And I cannot locate where the "Directing auth client to our private IP" stuff is implemented. How is the internal IP returned?

MasterServerPort(==50020 by default) doesn't have to be forwarded, I suppose.

**Comment by TLeonardUK** [comment]
>After the modification, connections from the local machine won't be directed to the internal IP, which increases the latency.
It won't just increase latency, it flat out just won't work in the majority of consumer networks and will result in a connection failure.

>However, I noted that others who also use port forwarding seem not to have this problem.
Yes because they aren't recieving connections coming from 127.0.0.1, so they won't encounter this.

>Will it work if the client loses connection after redirecting and undoes the redirection?
If the client loses connection they will have to go through the entire connection process again, which will result in the same result.

> And I cannot locate where the "Directing auth client to our private IP" stuff is implemented. How is the internal IP returned?

The LAN and WAN IP's are retrieved using the functions in this file:
https://github.com/TLeonardUK/ds3os/blob/main/Source/Server/Core/Network/NetUtils.cpp

Redirection happens in two places:
Line ~88 
https://github.com/TLeonardUK/ds3os/blob/main/Source/Server/Server/LoginService/LoginClient.cpp

Line ~256
https://github.com/TLeonardUK/ds3os/blob/main/Source/Server/Server/AuthService/AuthClient.cpp

> MasterServerPort(==50020 by default) doesn't have to be forwarded, I suppose.
Correct, the master server is an outgoing connection. I don't expect anyone to be running their own master servers so nobody needs to forward the ports it requires.
