### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by SoundFX87** [TLeonardUK/ds3os#18]
Hello, 
I'm running into a error when starting the server. I've gone through the readme multiple times to verify I didn't miss anything. When starting the server I get to server is running, then the follow error appears. 

"Recieved error when trying to advertise server on master server. Response was not valid json."

Please advise.

Edit: Additionally, my Loader does not see any other available servers. I thought a test server was active.

**Comment by TLeonardUK** [comment]
That's because the server used to register and display active servers is down at the moment, I'll reset it shortly. Be aware this whole setup is currently WIP and in development, don't expect the master server to always be active.

You can import server config files to join servers while it's offline.
