### ISSUE TITLE
False flag?

### ISSUE THREAD

**Issue by doctorcontradict** [TLeonardUK/ds3os#204]
I just tried to install the experimental build for dark souls 2 private server and upon opening the zip file and my anti virus flagged it as some kind of Trojan? I'm kinda confused myself.

**Comment by TLeonardUK** [comment]
See the many other issues surrounding this.

https://github.com/TLeonardUK/ds3os/issues/148

It's a false flag, this happens every time a new release comes out, because in windows eyes it's unfamiliar, does process injection related things (common things that malware does as well), and isn't signed (I have no intention of paying for certificates for this project either, they aren't cheap).

The code that runs in the loader/injector is minimal, it's trivial to read through it yourself if your worried.

**Comment by doctorcontradict** [comment]
Thanks for the speedily reply I looked through some of the code and I'm curious if my antivirus flagged and quarantined it does the mod still work? I also love all the work you guys put into making dark souls 2 co op function.
