### ISSUE TITLE
about private server

### ISSUE THREAD

**Issue by A-new-b** [TLeonardUK/ds3os#43]
Hello, author, thanks to your project，but I have a problem in using this os.
my friends try to connect my server, I can see him in log, but he failed with disconnect.
this is the log.
![图片](https://user-images.githubusercontent.com/43344034/151103894-be44e5e6-8318-463f-b982-d8221d161223.png)
i don't know why.
In his screen .
![图片](https://user-images.githubusercontent.com/43344034/151103945-5b6c6a2e-43ca-4aed-a023-e25e75c11e45.png)
for configration, I am using frp to have a public ip,and i dont have ds3 in my host PC,does it matter?

**Comment by TLeonardUK** [comment]
The server host doesn't have to have DS3 installed, thats not an issue.

Make sure you set ServerPrivateHostname to your private (LAN) ip and ServerHostname to your public (WAN) ip address. There shouldn't be anything else required.

**Comment by A-new-b** [comment]
Thanks for your reply, I have found the cause of the problem, if you use frp to map your private port to pulic port，you have to keep the private ip and the public ip the same.According to this, I guess the auth service will follow the private ip,right?For I haven't detected the flow on 50000 and 50020 on my service if I use 127.0.0.1 for my private ip.

**Comment by TLeonardUK** [comment]
For reference the way it determines what IP address to send to the user is fairly simple:
- The loader gets the players external IP address, if thats the same as the public ip defined for the server, they are redirected to the servers private IP - As its assumed they are on the same LAN. Otherwise they are directed to the private ip.

CGNAT or unusual mapping of IP addresses may cause issues with this setup.

**Comment by TLeonardUK** [comment]
https://github.com/TLeonardUK/ds3os/discussions/categories/help-support

Can you put help requests in there please, trying to keep the issues list for bug reports.
