### ISSUE TITLE
Cannot see summon signs as the host of private server

### ISSUE THREAD

**Issue by Beveragio** [TLeonardUK/ds3os#66]
Hi, I'm hosting a private server to continue my co-op playthrough with friends while the official servers are down.
They can see my summon sign without issue, but I can't see theirs. Did I do something wrong? I can see my friend's ghosts running around at the bonfire, and they can summon me without issues.

**Comment by dave-ml-xcv** [comment]
I'm having the same issue. Server seems to be working fine and detects both me and my friend, tracks our locations correctly etc. I can see his phantom when we are trying to drop signs but neither of us can see our summon signs (we are both embered).

We are trying to achieve this in Undead settlement - he has killed the boss in that area but I have not. By that logic I should be able to see his sign but I'm not able to. This was the same both in my server as well as the ?ServerName? 'official' server.

**Comment by TLeonardUK** [comment]
Are you using password matching?

**Comment by dave-ml-xcv** [comment]
We tried both with and without passwords - same result (or lack thereof).

**Comment by TLeonardUK** [comment]
Hum, honestly I'm not sure, I can't reproduce it locally, I can see both signs fine when they are in a state when they should be able to see each others.

I did just fix a seperate sign related change, that might have been the caused other sign issues for the client. If you monitor https://github.com/TLeonardUK/ds3os/releases a release 0.12 is building at the moment, which has this change, give it a try and see if that helps.

**Comment by Beveragio** [comment]
Ok, so, I was trying to summon at the ringed city inner wall for Midir. It turns out in my case I was an idiot - our first time through Midir bugged out and didn't fall into the pit from the bridge properly in my game, so he hadn't spawned as a boss even though we beat him at the bridge, I just had to go and do it again.
However I see other people are having similar problems so hopefully the new build helps them out.

**Comment by dave-ml-xcv** [comment]
@TLeonardUK Thanks for the update mate, I will check it out later on and keep you posted probably tomorrow or the next few days.

**Comment by dave-ml-xcv** [comment]
@TLeonardUK we tried with the newest version (0.14 at the time of writing) and still no dice. My friend had defeated the area boss in Settlement so he tried dropping his sign for me (who was embered and the Greatwood boss alive with fog gate) but his sign still never showed. I have not seen *anyone*'s summon signs, not just my friend's, but it's not a busy area so might be just no people there.

This happened both on ?ServerName? as well as the private server running on my end. I should also mention he is unable to forward ports on his end, since he is using a wifi network supplied by his building maintainers. He has had no issues with logging on and launching the game etc, we just cannot see any signs.

Is there a chance he absolutely needs the ports forwarded for co-op to work??
