### ISSUE TITLE
Support for DSR

### ISSUE THREAD

**Issue by TarnishedKuma** [TLeonardUK/ds3os#89]
Hello,

I like the idea of creating an alternative server during official server taking down period! Just wondering if the network setting for DS3 and DSR are similar enough and would DSR get this support in future? Appreciate you work!

**Comment by TLeonardUK** [comment]
From what I've seen of DSR, the networking is different enough that its going to be a fairly significant amount of work to do, but may happen in future.

Right now I just want to get DS3OS fully working, then I'll probably take a poke at DS2.

**Comment by MasterDrake** [comment]
"Right now I just want to get DS3OS fully working, then I'll probably take a poke at DS2."
Wouldn't be better to take a poke to Elden Ring instead?
Just curious about your intentions.
BTW, amazing job!!!

**Comment by TLeonardUK** [comment]
I have no intention of touching ER. To early in the games lifecycle, to high a probability people will use the servers purely for piracy.

**Comment by MasterDrake** [comment]
Is it possible to use it for piracy?
Steam emulators works with this project as well?

Bu still, it would be a good way to help **legit** people playing together, you know :)
Hope you'll think about it

**Comment by SirGouki** [comment]
Steam emulators hook redirect steam api calls with their own code.  This is how they "allow" piracy, despite their usefulness in legit things such as what Nucleus Coop does (which is to run the game multiple times on the same computer and use one such steam emulator to route all traffic over loopback and LAN addresses), allowing for simulated split screen (or in my case, one instance running on my left monitor, and another running on my right monitor so I can co-op games with my brother that I have bought and he either doesn't own, or can't run because his computer is one of those HP office desktops that don't even have room in the case for a dedicated GPU).

Unfortunately, as with all emulators, if they bypass checks to see if you legitimately own the game people *will* use it for piracy (Which many of them do as a feature, because the intent was to remove DRM from legitimately purchased games so you could do things like run them offline. Also going around steam servers to do multiplayer over LAN/loopback also bypasses some authorization checks steam would be doing if you were connecting to their multiplayer servers).  ER is likely runnable with a current steam emulator, but I've got no reason to check it as that's a game I wont need LAN emulation for.

**Comment by Pav-Osmolski** [comment]
> I have no intention of touching ER. To early in the games lifecycle, to high a probability people will use the servers purely for piracy.

You are a good person, and I completely agree that it is too early in the games lifecycle. It would make more sense to expand Open Server to accomodate ER a year down the line (at the very least), especially once the modding community has exploded to the same degree as DS3. With DS3 we are spoilt for choice with Cinders, Ashes and Convergence etc. Indeed, it would serve the PvP community wonderfully. I am not sure if ER has two server pools like with DS3, and if it relegates detected "cheaters" to their own server, but I'm assuming that since it relies on EAC it would simply prevent online access altogether if people attempt to run with modded content.

**Comment by Grammernatzi** [comment]
I definitely think an Elden Ring Open Server should happen at some point, because there is no currently no way to play mods online at all. We had a way with Dark Souls 3, but we do not have one here, because turning EAC off means no online play whatsoever. That said, I'm more than okay with a grace period, this game is huge and I don't need mods for it for a while. But it's certainly a good idea later down the line.

**Comment by TLeonardUK** [comment]
Closing this, as handling this (if its done) will end up being done in a seperate repo.
