### ISSUE TITLE
character represented by universal-character-name 'char' cannot be represented in the current code page

### ISSUE THREAD

**Issue by Adephx** [TLeonardUK/ds3os#9]
```    int ret = snprintf(buffer_to_use, 256, "%s \u002A %-7s \u002A %s\n", time_buffer, Level, Log);
    if (ret >= 256)
    {
        buffer_to_use = new char[ret + 1];
        snprintf(buffer_to_use, 256, "%s \u002A %-7s \u002A %s\n", time_buffer, Level, Log);
        buffer_to_use[ret] = '\0';
    }
```

Program won't compile with the \u00B3 UTF-8 character. I also tried L\u00B3 and u8\u00B3. Any ideas? It works if I use another char, for example * > \u002A.

Also side question, I have noticed that the Loader.exe in your `Release v0.6.0.0-main` package is sitting at a whopping 147MB and the folder only contains two files, Loader.exe and Loader.pdb.

My build compiles as following, but seems to work just fine. Is it safe to assume that you are compiling the dependences directly into the executable file? Could you walk me through the process?

```
15. 09. 2021  09:26               414 Loader.deps.json
15. 09. 2021  08:28           740.352 Loader.dll
15. 09. 2021  08:28           311.296 Loader.exe
15. 09. 2021  08:28            19.972 Loader.pdb
15. 09. 2021  09:26               265 Loader.runtimeconfig.dev.json
15. 09. 2021  09:26               154 Loader.runtimeconfig.json
15. 09. 2021  09:28    <DIR>          ref
15. 09. 2021  08:28           198.144 Loader.dll
```

**Comment by TLeonardUK** [comment]
Interesting, I'm not sure about that, what codepage does your system run on? You could just replace it with a | if needed, its only using the box-drawing line character to avoid gaps.

As for the large exe, it's because its generated as a standalone exe. Under .NET 5.0 this causes it to package parts of the .NET runtime with the exe rather than the user having to install a runtime seperately. This may or may not be the best way to handle this, .NET development is not really my area, but it seemed like the best choice for compatibility when I was setting up the release build scripts. I'm open to better suggestions.

You can see how the packaging is done here, the "Package DotNet" is the one you would be interested in.
https://github.com/TLeonardUK/ds3os/blob/main/.github/workflows/release.yml

**Comment by TLeonardUK** [comment]
Also as an aside. There is an option when packaging .NET applications to trim the executable by removing methods in the packed assemblies that are not actively used by the application. I experimented a bit with this before and it reduced the size by about half, but unfortunately it also made the executables crash almost immediately. Might be something to investigate further.

**Comment by Jeyyu** [comment]
> Also side question, I have noticed that the Loader.exe in your Release v0.6.0.0-main package is sitting at a whopping 147MB and the folder only contains two files, Loader.exe and Loader.pdb.
> 
> My build compiles as following, but seems to work just fine. Is it safe to assume that you are compiling the dependences directly into the executable file? Could you walk me through the process?


To compile a singel exe file u need to change some settings in the .csproj:

For a Single exe file with no build in runtime (needs .Net 5.0 installed on OS) (~ 1 MB):
**add under  PropertyGroup** the following statments

```
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
<SelfContained>False</SelfContained>
<PublishSingleFile>true</PublishSingleFile>
<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
```

For a Single exe file with build in runtime (~ 150 MB untrimmed , ~70 trimmed):
**add under  PropertyGroup** the following statments

```
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
<SelfContained>true</SelfContained>
<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
<PublishSingleFile>true</PublishSingleFile>
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>Link</TrimMode>
```
U can delete PublishTrimmed and TrimMode if u want to go untrimmed, sometimes its better, it can cause weird behavior. 
Since u mention the big size of the Loader I would suggest to just compile it with no build in runtime and make sure u have .Net 5.0 installed on your OS.

### Note:
to compile the publish settings **u need to compile it via a publish command like the CLI version donet publish**

**Comment by Adephx** [comment]
> Interesting, I'm not sure about that, what codepage does your system run on? You could just replace it with a | if needed, its only using the box-drawing line character to avoid gaps.
> 
> As for the large exe, it's because its generated as a standalone exe. Under .NET 5.0 this causes it to package parts of the .NET runtime with the exe rather than the user having to install a runtime seperately. This may or may not be the best way to handle this, .NET development is not really my area, but it seemed like the best choice for compatibility when I was setting up the release build scripts. I'm open to better suggestions.
> 
> You can see how the packaging is done here, the "Package DotNet" is the one you would be interested in.
> https://github.com/TLeonardUK/ds3os/blob/main/.github/workflows/release.yml

I'm running on 852 | Slavic (Latin II)

**Comment by TLeonardUK** [comment]
Try with latest, I switched those characters for the hex utf-8 chars. From what I read on the internet, that should solve this.

**Comment by Adephx** [comment]
Works perfectly now.
